### ISSUE TITLE
Custom header flicker

### ISSUE THREAD

**Issue by DaveRabelink** [jenkinsci/customizable-header-plugin#48] opened 2023-11-14 11:42 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server

### Reproduction steps

Enable custom header
Refresh any page in Jenkins.

### Expected Results

Smooth transitions between pages just like when custom header is not enabled

### Actual Results

The header is repainted. It looks ugly and distracts.

**Comment by DaveRabelink** [comment] 2023-11-14 11:46
Specially when the header is "Thin header" in settings.

It seems the original header is painted which moves all page contents down and then the new thin header is painted, moving all page contents up again.

**Comment by lemeurherve** [comment] 2023-11-14 12:10
Duplicate of #22

**Comment by mawinter69** [comment] 2023-11-14 20:15
yes most likely this is the cause. It happens when using jpg or png images that do not have the correct size. If you have a svg that works well.

**Comment by DaveRabelink** [comment] 2023-11-15 09:12
Well it is more than that.
You can actually see that a "default" header is painted first and then the header is painted in the new style.
When the custom header has a different background color (eg red) compared to the original header (which is black), a refresh of the page or clicking on jobs etc will show that first a black background is painted and then the red custom one.

This makes the complete header flicker. The thin setting also makes the contents of the page jump vertically from the normal header height to the custom header height.

I did not try setting different logo sizes, but I can imagine that this also makes a difference between the original header and the custom one.

Overall it seems that the custom header painting is done after the original one. IMHO the custom header should replace existing painting so there is no difference in refresh or displaying of pages.

**Comment by mawinter69** [comment] 2023-11-15 09:42
The custom header is not painted over the original header. It replaces it from the beginning. But the styling is computed dynamically on page load and I can't change that, as this is user dependent.
Is your Jenkins maybe under heavy load so that loading the css is delayed?
Maybe it is also due to the fact that the css is loaded only in the body and not in the head of the html. I think I can change that with a page decorator

**Comment by mawinter69** [comment] 2023-11-15 10:57
@DaveRabelink @lemeurherve 
Can you please check if https://repo.jenkins-ci.org/artifactory/incrementals/io/jenkins/plugins/customizable-header/51.vf593a_8b_1a_c12/customizable-header-51.vf593a_8b_1a_c12.hpi solves or improves the problem?

**Closed** 2023-11-16 08:47 UTC
Labels: bug

**Comment by mawinter69** [comment] 2023-11-16 08:49
I've released my change. In case you still experience the problem please reopen.

**Comment by lemeurherve** [comment] 2023-11-16 08:56
Sorry didn't have time to test the incremental, but I'll let you know when we'll have deployed this new version on infra.ci.jenkins.io.

**Comment by lemeurherve** [comment] 2023-11-17 18:41
> I've released my change. In case you still experience the problem please reopen.

LGTM, thanks @mawinter69!
